### ISSUE TITLE
bower.json conflict with grunt-wiredep

### ISSUE THREAD

**Issue by klammbueddel** [gilbox/infinite-slider#4]
> grunt-wiredep is a Grunt plug-in, which finds your components and injects them directly into the HTML file you specify

The way the optional dependencies are maintained in the bower.json results in conflicts when using automatic dependency resolver like grunt-wiredep. Both, hamster ~0.3.0 (from infinite-slider) and "hamsterjs": ">=1.0.2" from angular-mousewheel will be injected which will fail due to incompatible APIs.

**Comment by gilbox** [comment]
Thanks @klammbueddel if you submit a PR it would be much appreciated.

**Comment by klammbueddel** [comment]
I think the default should be angular-mousewheel with hamsterjs > 1.0.2 since it is more up to date, see #5

**Comment by gilbox** [comment]
thanks
