### ISSUE TITLE
Directive doesn't work with last Angular version (1.3.11)

### ISSUE THREAD

**Issue by nachoargentina** [gilbox/infinite-slider#6]
Hi!
I was trying this out with AngularJS v1.3.11 and couldn't get the example to work in any way.
After a lot of changes to try to find out what the issue was, I thought of changing to the angular version you are using in the example (1.2.3) and that actually solved the problem!
Here's a Plunker link to show the problem:
http://plnkr.co/edit/oUDsX1tinV73OpRgzMeW?p=preview

Check that in the HTML I'm importing angular version 1.3.11. You will see it doesn't work. If you change the Angular version to 1.2.3, it will start working.
Do you know why the directive is not working on the last angular version? Is there a quick fix to make it work?
Thanks you so much for your time, the directive is top-notch and would love to use it!

**Comment by gilbox** [comment]
The latest I tried it with is 1.3.0-beta.11... I'll see what I can find out.

**Comment by gilbox** [comment]
Ok this seems to be related to issue #3 ... add `disable-drag="false"` to the `infinite-slider` element. 

http://plnkr.co/edit/xBS9uAHe4mOzzCNVkqAU?p=preview

This bug is probably an easy fix. If you'd like to have at it would be greatly appreciated.

**Comment by nachoargentina** [comment]
Did I mention you are the greatest? Thank you so much! Adding that property solved the issue.
I will try to fix it in the library and leave a PR for you to check. Thanks again!

**Comment by gilbox** [comment]
you're welcome :-)
