### ISSUE TITLE
Does not work with Angular 1.3.x

### ISSUE THREAD

**Issue by DodekaHydra** [gilbox/infinite-slider#7]
I've been trying to integrate this into my project and it seems Angular 1.3.x is the problem.

There were some breaking changes with the migration from 1.2 to 1.3, particularly with how the compilation phase of directives are handled.

https://docs.angularjs.org/guide/migration

**Comment by gilbox** [comment]
https://github.com/gilbox/infinite-slider/issues/6

**Comment by DodekaHydra** [comment]
Aah I didn't think to check closed issues. Thanks for the quick reply.

This slider is great, by the way. I'll show you what I'm working on when it's released.
